### ISSUE TITLE
Scripts should take command line arguments

### ISSUE THREAD

**Issue by ilyash-b** [JacFearsome/powershell-scripts#1]
For now, these scripts are anti-automation because they are interactive.

**Comment by jrussellfreelance** [comment]
Valid point.  I originally created this repo for the purpose of quickly running interactive scripts, but I will update them to take command line arguments.

**Comment by jrussellfreelance** [comment]
I've updated most of the scripts to take parameters instead of using Read-Host. I will add error-catching for blank parameter values in my next commit, as well as add comments explaining each parameter.

**Comment by ilyash-b** [comment]
> I've updated most of the scripts to take parameters instead of using Read-Host. I will add error-catching for blank parameter values in my next commit, as well as add comments explaining each parameter.

Looks like mandatory parameters can help.

https://blogs.technet.microsoft.com/heyscriptingguy/2011/05/22/use-powershell-to-make-mandatory-parameters/

**Comment by jrussellfreelance** [comment]
I've updated every script where parameters exist to use mandatory parameters.
